<a href="https://colab.research.google.com/github/bhagyasree2004/MachineLearning_Module/blob/main/FORECASTING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/AirPassengers.csv')
df.head()

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [ ]:
df.rename(columns={'Month': 'ds', '#Passengers': 'y'}, inplace=True)

In [ ]:
df.head()

        ds    y
0  1949-01  112
1  1949-02  118
2  1949-03  132
3  1949-04  129
4  1949-05  121

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ds      144 non-null    object
 1   y       144 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.4+ KB

In [ ]:
# convert it into date object
df['ds']=pd.to_datetime(df['ds'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ds      144 non-null    datetime64[ns]
 1   y       144 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 2.4 KB

In [ ]:
#fiting the prohent model
from prophet import Prophet
model=Prophet()
model.fit(df)

INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.